/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"Top Menu","top-menu",0),
(3,"Social Links Menu","social-links-menu",0),
(4,"Our Services","our-services",0),
(5,"account","account",0),
(6,"accountant","accountant",0),
(7,"blog","blog",0),
(8,"business","business",0),
(9,"camera","camera",0),
(10,"Consultancy","consultancy",0),
(11,"corporate","corporate",0),
(12,"cyclone","cyclone",0),
(13,"cyclonethemes","cyclonethemes",0),
(14,"management","management",0),
(15,"manager","manager",0),
(16,"media","media",0),
(17,"menager","menager",0),
(18,"motivation","motivation",0),
(19,"photo","photo",0),
(20,"theme","theme",0),
(21,"themeforest","themeforest",0),
(22,"travel","travel",0),
(23,"wordcamp","wordcamp",0),
(24,"wordpress","wordpress",0),
(25,"Clients","clients",0),
(26,"construction gallery","construction-gallery",0),
(27,"construction services","construction-services",0),
(28,"Doctors","doctors",0),
(29,"Our Chefs","our-chefs",0),
(30,"OUR Teachers","our-teachers",0),
(31,"Slider","slider",0),
(32,"Team","team",0),
(33,"Testimonial","testimonial",0),
(34,"Footer Menu","footer-menu",0),
(35,"Main Menu","main-menu",0),
(36,"Useful Links","useful-links",0);
